name: Setup .env

on:
  push:
    branches:
      - main  # Trigger this on pushes to main

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
